Formatics/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Formatics.Models
{
    public class Alert
    {
        //A set amount of alert objects will be created for every intervention
        [Key]
        public int AlertId { get; set; }


        [Display(Name = "Type")]
        public string type { get; set; }


        [Display(Name = "Frequency")] //If applicable and not on condition.
        public int frequency { get; set; }

        [Display(Name = "Time")]
        [DataType(DataType.DateTime)]
        public DateTime time { get; set; } //time of day sent out


        [Display(Name = "Description")] //If applicable and not on condition.
        public string description { get; set; }



    }
}

Formatics/Models/Diagnosis.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Formatics.Models
{
    public class Diagnosis
    {
        [Key]
        public int DiagnosisId { get; set; }

        [ForeignKey("Intervention")]
        public int InterventionId { get; set; }
        public Intervention Intervention { get; set; }

        [Display(Name = "Category")]
        public string category { get; set; }

        [Display(Name = "Date Diagnosed")]
        [DataType(DataType.DateTime)]
        public DateTime dateDiagnosed { get; set; }

        [Display(Name = "Is Current")]
        public bool isCurrent { get; set; }

    }
}

Formatics/Controllers/FrontEndController.cs
using Formatics.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Api.V2010.Account;

namespace Formatics.Controllers
{
    public class FrontEndController : Controller
    {
        // GET: FrontEnd
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View();
        }

        // GET: FrontEnd/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FrontEnd/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FrontEnd/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FrontEnd/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FrontEnd/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FrontEnd/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FrontEnd/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return PartialView();

            }
        }
 
        public ActionResult Perscription() //Feedback review paqge
        {
            return PartialView();

        }

        //Dashboard
        public ActionResult Personalization()
        {
            return PartialView();
        }

        public ActionResult Resources()
        {
            return PartialView();
        }

       

        public ActionResult TreatmentGlimpse()
        {
            return PartialView();
        }

        // GET: 
        [HttpPost]
        public ActionResult Mood(int FeedbackId, Feedback feedback) //Feedback review paqge
        {
            string userId = User.Identity.GetUserId();
            Patient patient = db.patients.Where(e => e.ApplicationId == userId).SingleOrDefault();
            feedback.date = DateTime.Now;

            Feedback feedback1 = new Feedback(); 
            feedback1.comments = feedback.comments;
            feedback1.rating = feedback.rating;
            feedback1.date = feedback.date;
            feedback1.PatientNumber = patient.PatientNumber;
            feedback1.type = "Mood";
            feedback1.StepId = feedback.StepId;
            db.feedbacks.Add(feedback1);
            ViewBag.PartialStyle = "display: none";

            db.SaveChanges();

            return RedirectToAction("Index", "Intervention");
        }

        [HttpPost]
        public ActionResult Condition(int FeedbackId, Feedback feedback) //Feedback review paqge
        {
            string userId = User.Identity.GetUserId();
            Patient patient = db.patients.Where(e => e.ApplicationId == userId).SingleOrDefault();
            feedback.date = DateTime.Now;
            Feedback feedback1 = new Feedback();
            feedback1.comments = feedback.comments;
            feedback1.rating = feedback.rating;
            feedback1.date = feedback.date;
            feedback1.type = "Condition";
            feedback1.StepId = feedback.StepId;
            feedback1.PatientNumber = patient.PatientNumber;
            db.feedbacks.Add(feedback1);
            ViewBag.Name = "display: none";

            db.SaveChanges();
            return RedirectToAction("Index", "Intervention");
        }

        [HttpPost]
        public ActionResult Alert(int AlertId, Alert alert)
        {
            Alert alert1 = new Alert();
            alert1.description = alert.description;
            alert1.description = alert.description;
            alert1.frequency = alert.frequency;
            alert1.type = "Appointment";
            alert1.time = alert.time.Date;
            db.alerts.Add(alert1);
            db.SaveChanges();

            TwilioClient.Init(twillio.accountSid, twillio.authToken);

            var message = MessageResource.Create(
                body: "Your Appointment has been sent.  We will send you a reminder the day of",
                from: new Twilio.Types.PhoneNumber("+12564877936"),
                to: new Twilio.Types.PhoneNumber("+14143887275")
            );
            //twillio

            return RedirectToAction("Index", "Intervention");

        }
        public ActionResult Schedule() //View page
        {
            return View();
        }

        // GET: FrontEnd/Edit/5
        public ActionResult SubmitFeedback(int id)
        {
            return PartialView();
        }

        // POST: FrontEnd/Edit/5
        [HttpPost]
        public ActionResult SubmitFeedback(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return PartialView();
            }
        }


        public ActionResult DailyPlanner()
        {
            return PartialView();
        }

        // GET: 
        public ActionResult Diagnosis() //Feedback review paqge
        {
            return PartialView();
        }



    }
}

Formatics/Views/FrontEnd/FeedbackReview.cshtml
@model IEnumerable<Formatics.Models.Feedback>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StepId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.comments)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StepId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatientNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.comments)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FeedbackId }) |
            @Html.ActionLink("Details", "Details", new { id=item.FeedbackId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FeedbackId })
        </td>
    </tr>
}

</table>

Formatics/Views/FrontEnd/Schedule.cshtml
@model IEnumerable<Formatics.Models.Steps>


<table id="ScheduleView" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InterventionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.InterventionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StepId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StepId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StepId })
        </td>
    </tr>
}

</table>

Formatics/Views/FrontEnd/_Alerts.cshtml
@model IEnumerable<Formatics.Models.Alert>


<table class="col-sm-4" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.frequency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.type)
    </td>
    <td hidden>
        @Html.DisplayFor(modelItem => item.frequency)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.time)
    </td>
    <td hidden>
        @Html.DisplayFor(modelItem => item.description)
    </td>
    @*@Html.ActionLink("Map", "Map", new { AlertId = item.AlertId }, new { @class = "btn btn-default" })*@

</tr>
    }

</table>
<br />
<br />

Formatics/Views/FrontEnd/_DailyPlanner.cshtml
@model IEnumerable<Formatics.Models.Steps>


<table id = "DailyPlannerView" class="table" hidden>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InterventionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.InterventionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StepId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StepId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StepId })
        </td>
    </tr>
}

</table>

Formatics/Views/FrontEnd/_MedicalHistory.cshtml
@model IEnumerable<Formatics.Models.Medicine>

    <div style="border:double;  border-color: olivedrab">
        <br />
        <h3>Medicine</h3>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.drugClass)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.isCurrent)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.drugClass)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.isCurrent)
                    </td>

                </tr>
            }

        </table>
    </div>

Formatics/Views/FrontEnd/_Perscription.cshtml
@model Formatics.Models.Medicine

<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.drugClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.drugClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MedicineId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Formatics/Views/FrontEnd/_Results.cshtml
@model Formatics.Models.Alert

<div>
    <h4>Alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.frequency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.frequency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>
<p>

</p>

Formatics/Views/FrontEnd/_SetAppointment.cshtml
@model Formatics.Models.Alert

@using (Html.BeginForm("Alert", "Frontend", new { AlertId = Model.AlertId}, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlertId)

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.frequency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.frequency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.frequency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Formatics/Views/FrontEnd/_SubmitCondition.cshtml
@model Formatics.Models.Feedback


@using (Html.BeginForm("Condition", "FrontEnd", new { FeedbackId = Model.FeedbackId }, FormMethod.Post)) 
{
    <div id="SubmitConditionView" style="@ViewBag.Name">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>How do you feel about your condition today?</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div hidden class="form-group">
                @Html.LabelFor(model => model.StepId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StepId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StepId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div hidden class="form-group">
                @Html.LabelFor(model => model.PatientNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PatientNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" }) 
                <div class="col-md-10">
                    <span>(1-10)</span>
                    @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.comments, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Formatics/Views/FrontEnd/_SubmitMood.cshtml
@model Formatics.Models.Feedback


@using (Html.BeginForm("Mood", "FrontEnd", new { FeedbackId = Model.FeedbackId }, FormMethod.Post )) 
{
    <div id="SubmitMoodView" style="@ViewBag.PartialStyle">

    @Html.AntiForgeryToken()
    
        <div class="form-horizontal">
            <h4>What is your overall mood today?</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div hidden class="form-group">
                @Html.LabelFor(model => model.StepId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StepId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StepId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div hidden class="form-group">
                @Html.LabelFor(model => model.PatientNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PatientNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientNumber, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" }) 
                <div class="col-md-10">
                    <span>(1-10)</span>
                    @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.comments, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Formatics/Views/FrontEnd/_TreatmentGlimpse.cshtml
@model Formatics.Models.Steps

<div id="TreatementGlimpseView" hidden>
    <h4>Treatment Plan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InterventionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterventionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>

Formatics/Views/FrontEnd/_detailsMedicine.cshtml
@model Formatics.Models.Medicine
@{ 
    

}
    <table id="DetailsMedicineView">
        <hr />

        @foreach (var item in Model.symptoms)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item)

                </td>

            </tr>
        }

        @foreach (var item in Model.ingredients)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item)

                </td>

            </tr>
        }

    </table>       

Formatics/Views/FrontEnd/_ingredients.cshtml
@model IEnumerable<String>

@{

    var ingredients = Model;
}
<div style="border:double;  border-color: olivedrab">

    <h4>Ingredients</h4>
    <table class="table">


        @foreach (var item in ingredients)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item)
                </td>
            </tr>
        }

    </table>
</div>

Formatics/Views/FrontEnd/_symptoms.cshtml
@model IEnumerable<String>

@{

    var symptoms = Model;
}
    <div style="border:double;  border-color: olivedrab">
        <h4>Symptoms</h4>
        <table class="table">


            @foreach (var item in symptoms)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item)
                    </td>
                </tr>
            }

        </table>
    </div>